export const res = {
  "id": 1,
  "name": "Запчасти",
  "parent": {
      "id": 6,
      "name": "Авто Товары",
      "old_group_id": null,
      "slug": "avto-tovary",
      "plus": "",
      "minus": "",
      "full_plus": "",
      "full_minus": "",
      "lft": 1,
      "rght": 3102,
      "tree_id": 1,
      "level": 0,
      "parent": null,
      "tags": []
  },
  "children": [
      {
          "id": 21,
          "name": "Аккумуляторы",
          "old_group_id": null,
          "slug": "akkumuljatory",
          "plus": "аккум",
          "minus": "вававав",
          "full_plus": "",
          "full_minus": "",
          "lft": 31,
          "rght": 54,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 38,
          "name": "Воздушная Система",
          "old_group_id": null,
          "slug": "vozdushnaja-sistema",
          "plus": "компресс",
          "minus": "кондиц",
          "full_plus": "",
          "full_minus": "",
          "lft": 55,
          "rght": 68,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 36,
          "name": "Выхлопная Система",
          "old_group_id": null,
          "slug": "glushitel",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 69,
          "rght": 96,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 33,
          "name": "Детали Двигателя",
          "old_group_id": null,
          "slug": "detali-dvigatelja",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 97,
          "rght": 384,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 37,
          "name": "Инструменты",
          "old_group_id": null,
          "slug": "instrumenty",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 385,
          "rght": 414,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 22,
          "name": "Колеса Шины",
          "old_group_id": null,
          "slug": "shiny",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 415,
          "rght": 462,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 24,
          "name": "Кузовные Детали",
          "old_group_id": null,
          "slug": "kuzovnye-detali",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 463,
          "rght": 1010,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 28,
          "name": "Отопление Климат Контроль",
          "old_group_id": null,
          "slug": "otoplenie-klimat-kontrol",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1011,
          "rght": 1084,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 40,
          "name": "Охлаждение",
          "old_group_id": null,
          "slug": "ohlazhdenie",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1085,
          "rght": 1232,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 25,
          "name": "Подвеска",
          "old_group_id": null,
          "slug": "podveska",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1233,
          "rght": 1418,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 27,
          "name": "Рулевое Управление",
          "old_group_id": null,
          "slug": "rulevoe-upravlenie",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1419,
          "rght": 1488,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 31,
          "name": "Салон Интерьер",
          "old_group_id": null,
          "slug": "salon-interer",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1489,
          "rght": 1766,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 39,
          "name": "Стекла, омыватели, стеклоподъемники",
          "old_group_id": null,
          "slug": "stekla-omyvateli-steklopodemniki",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1767,
          "rght": 1828,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 29,
          "name": "Топливная Система",
          "old_group_id": null,
          "slug": "toplivnaja-sistema",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1829,
          "rght": 1892,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 23,
          "name": "Тормозная Система",
          "old_group_id": null,
          "slug": "tormoznaja-sistema",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 1893,
          "rght": 2032,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 26,
          "name": "Трансмиссия",
          "old_group_id": null,
          "slug": "transmissija",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 2033,
          "rght": 2310,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 30,
          "name": "Фары, Освещение, Сигнализация",
          "old_group_id": null,
          "slug": "fary-osveschenie-signalizatsija",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 2311,
          "rght": 2458,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 35,
          "name": "Фильтры и Ремни",
          "old_group_id": null,
          "slug": "filtry",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 2459,
          "rght": 2554,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      },
      {
          "id": 34,
          "name": "Электрооборудование",
          "old_group_id": null,
          "slug": "elektrooborudovanie",
          "plus": "",
          "minus": "",
          "full_plus": "",
          "full_minus": "",
          "lft": 2555,
          "rght": 3090,
          "tree_id": 1,
          "level": 2,
          "parent": 1,
          "tags": []
      }
  ],
  "slug": "zapchasti"
}